[package]
name = "resident-engine"
description = "Minimal game engine: wgpu 30 + shipyard ECS + winit"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
log.workspace = true
pollster.workspace = true
puffin = "0.20.0"
shipyard.workspace = true
thiserror.workspace = true
w-gui = "0.22.41"
wgpu.workspace = true
winit.workspace = true
