[package]
name = "resident-engine"
description = "Minimal game engine: wgpu 30 + shipyard ECS + winit"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
log.workspace = true
pollster.workspace = true
resident-gpu = { path = "../gpu" }
resident-profiler = { path = "../profiler" }
shipyard.workspace = true
thiserror.workspace = true
w-gui.workspace = true
wgpu.workspace = true
winit.workspace = true
